Add Logger Middleware
MikeAndrianov/wabi pull request #2
Opened 2020-10-16 19:09 UTC by MikeAndrianov

2020-10-16 19:19 UTC, IvanShamatov requested changes

2020-10-16 19:19 UTC, IvanShamatov commented on config.ru
> +app =
в config.ru нет смысла оборачивать в билдер
use Middleware::Logger
run App.new

и все будет работаь

2020-10-16 19:19 UTC, IvanShamatov commented on middleware/logger.rb
> +      @app = app
Используй рубишный Logger, прокидывай его внутрь как зависимость, тогда ты сможешь им управлять извне миддлвари

2020-10-16 19:19 UTC, IvanShamatov commented on middleware/logger.rb
> +      @app.call(env)
это не было оговорено, но обычно ожидается, что мы узнаем за сколько был выполнен запрос. JFYI

2020-10-16 19:19 UTC, IvanShamatov commented on middleware/logger.rb
> +      FileUtils.mkdir_p(LOGS_FOLDER) unless File.directory?(LOGS_FOLDER)
Вообще, хорошее девопс правило -- не писать логи в файл. Кому они в файле нужны?
Лучше всего логи писать в STDERR и STDOUT, потому что это не задача приложения, как хранить логи, и как их обрабатывать.

Из потока же их можно читать в разные сервисы (например, прямиков в амазон) или предназначенные специально для логротейтов штуки.

2020-10-16 19:19 UTC, IvanShamatov commented on middleware/logger.rb
> +    def environment
эта штука не является характеристикой самой миддлвари. Она должна приходить в качестве зависимости, например в new/call. ИЛИ быть глобальной. ДА-ДА, глобальной. (я уж не говорю, что ENV и есть глобальная переменная)

2020-10-16 19:19 UTC, IvanShamatov commented on middleware/logger.rb
> +      FILTERED_PARAMS.include?(key) ? '[FILTERED]' : value
А вот это классно, что подумал, но было бы неплохо тоже иметь возможность конфигурировать извне миддлвари этот параметр

2020-10-16 19:19 UTC, IvanShamatov commented on spec/middleware/logger_spec.rb
> +  let(:app) { instance_double(App) }
это излишнее
`let(:app) { ->(_){ [200, {}, []] }  }`
тоже хватило бы

2020-10-16 19:19 UTC, IvanShamatov commented on spec/middleware/logger_spec.rb
> +    allow(DateTime).to receive(:now).and_return(DateTime.new(2020, 10, 16))
уууух. ну ладно. надеюсь нам больше DateTime нигде в спеках не понадобится

2020-10-16 19:23 UTC, MikeAndrianov commented on spec/middleware/logger_spec.rb
> +    allow(DateTime).to receive(:now).and_return(DateTime.new(2020, 10, 16))
да, если вдруг понадобится, то подключу timecop

2020-10-17 15:59 UTC, IvanShamatov approved these changes

2020-10-17 15:59 UTC, merged